### ISSUE TITLE
Outdated es-419.json

### ISSUE THREAD

**Issue by coderdiaz** [coderdiaz/vue-cli-locale-es-419#1]
## Need
- Update the `es-419.json` file to new specs. This file is only for Latam Spanish.

Ref.
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-ui/locales/en.json

**Comment by caugner** [comment]
@coderdiaz I have added [`es-419` on Transifex](https://www.transifex.com/vuejs/vue-cli/language/es_419/) now.

I recommend translating the 117 untranslated keys directly here:
https://www.transifex.com/vuejs/vue-cli/translate/#es_419/$/148882921?q=translated%3Ano

Afterwards, the JSON file can be directly exported here (click on `cli-ui` and choose `Download for use`):
https://www.transifex.com/vuejs/vue-cli/language/es_419/

**Comment by coderdiaz** [comment]
@caugner Well, I check it out. 👍
